/* XPM */
static char * icon_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconColor3	m black	c red",
"o	s iconColor8	m black	c magenta",
"O	s iconGray7	m black	c #424242424242",
"+	s iconColor7	m white	c cyan",
"@	s iconColor5	m black	c blue",
"#	s iconColor6	m white	c yellow",
"$	s iconGray8	m black	c #212121212121",
"%	s iconColor2	m white	c white",
"&	s iconColor4	m white	c green",
"*	s iconGray3	m white	c #adadadadadad",
"=	s iconGray6	m black	c #636363636363",
"-	s iconColor1	m black	c black",
";	s iconGray4	m white	c #949494949494",
/* pixels */
"               .......          ",
"               .XoXoXO          ",
"               .oXoXoO          ",
"               .XoXoXO          ",
" ......O       .oXoXoO  ....... ",
" .+@+@+O       .XoXoXO  .#####O ",
" .@+@+@O       .OOOOOO  .#####O ",
" .+@+@+O                .#####O ",
" .@+@+@O                .#####O ",
" .+@+@+O       $$$$$    .#####O ",
" .OOOOOO     $$     $$  .OOOOOO ",
" ......O....$..    %% $         ",
" .&#&#&O.++$++O      % $        ",
" .#&#&#O.++$++O       %$        ",
" .&#&#&O.+$+++O       % $       ",
" .#&#&#O.+$+++O         $       ",
" .&#&#&O.+$+++O         $       ",
" .OOOOOO.O$OOOO         $       ",
" .........$*..........  $       ",
" .@@@@@O.#=$##O.XXXXXO $        ",
" .@@@@@O.#=$##O.XXXXXO $        ",
" .@@@@@O.##=$#O.XXXXXO-%;       ",
" .@@@@@O.###=$$.XXXX$$*-#;      ",
" .@@@@@O.#####O$$$$$==O-=.;     ",
" .OOOOOO.OOOOOO=OOOOOO=--X#;    ",
" ..................... =--=.;   ",
" .XoXoXO.&&&&&O.+@+@+O  =--X#;  ",
" .oXoXoO.&&&&&O.@@@@@O   =--=.; ",
" .XoXoXO.&&&&&O.+@+@+O    =--X#;",
" .oXoXoO.&&&&&O.@@@@@O     =--=$",
" .XoXoXO.&&&&&O.+@+@+O      =-$O",
" .OOOOOO.OOOOOO.OOOOOO       OOO"};
