/* XPM */
static char * icon_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #dededededede",
"X	s iconColor3	m black	c red",
"o	s iconColor8	m black	c magenta",
"O	s iconGray7	m black	c #424242424242",
"+	s iconColor6	m white	c yellow",
"@	s iconColor5	m black	c blue",
"#	s iconColor7	m white	c cyan",
"$	s iconGray8	m black	c #212121212121",
"%	s iconColor2	m white	c white",
"&	s iconColor4	m white	c green",
"*	s iconGray6	m black	c #636363636363",
"=	s iconColor1	m black	c black",
"-	s iconGray3	m white	c #adadadadadad",
";	s iconGray4	m white	c #949494949494",
/* pixels */
"                      .........                 ",
"                      .XoXoXoXO                 ",
"                      .oXoXoXoO                 ",
"                      .XoXoXoXO                 ",
"                      .oXoXoXoO                 ",
"                      .XoXoXoXO                 ",
"                      .oXoXoXoO                 ",
"                      .XoXoXoXO      .........  ",
"   .........          .OOOOOOOO      .+++++++O  ",
"   .@#@#@#@O                         .+++++++O  ",
"   .#@#@#@#O                         .+++++++O  ",
"   .@#@#@#@O                         .+++++++O  ",
"   .#@#@#@#O                         .+++++++O  ",
"   .@#@#@#@O                         .+++++++O  ",
"   .#@#@#@#O        $$$$$$$$         .+++++++O  ",
"   .@#@#@#@O      $$        $$       .OOOOOOOO  ",
"   .OOOOOOOO     $            $                 ",
"                $       %%%%   $                ",
"   ......... ..$......    %%%   $               ",
"   .&+&+&+&O .$######O     %%%   $              ",
"   .+&+&+&+O .$######O       %%  $              ",
"   .&+&+&+&O $#######O       %%   $             ",
"   .+&+&+&+O $#######O        %%  $             ",
"   .&+&+&+&O $#######O        %%  $             ",
"   .+&+&+&+O $#######O         %  $             ",
"   .&+&+&+&O $#######O         %  $             ",
"   .OOOOOOOO $OOOOOOOO            $             ",
"             $                    $             ",
"   ......... $........ .........  $             ",
"   .@@@@@@@O *$++++++O .XXXXXXXO $              ",
"   .@@@@@@@O *$++++++O .XXXXXXXO $              ",
"   .@@@@@@@O .*$+++++O .XXXXXXXO $              ",
"   .@@@@@@@O .+*$++++O .XXXXXXX==%-             ",
"   .@@@@@@@O .++*$+++O .XXXXXX$===+;            ",
"   .@@@@@@@O .+++*$$+O .XXXX$$=====+;           ",
"   .@@@@@@@O .++++**$$$$$$$$**X===X++;          ",
"   .OOOOOOOO OOOOOOOOO*OOOOOOOOO===X++;         ",
"                                 ===X++;        ",
"   ......... ......... .........  ===X++;       ",
"   .XoXoXoXO .&&&&&&&O .#@#@#@#O   ===X++;      ",
"   .oXoXoXoO .&&&&&&&O .@@@@@@@O    ===X++;     ",
"   .XoXoXoXO .&&&&&&&O .#@#@#@#O     ===X++;    ",
"   .oXoXoXoO .&&&&&&&O .@@@@@@@O      ===X++;   ",
"   .XoXoXoXO .&&&&&&&O .#@#@#@#O       ===X++;  ",
"   .oXoXoXoO .&&&&&&&O .@@@@@@@O        ===X+$  ",
"   .XoXoXoXO .&&&&&&&O .#@#@#@#O         ==$$O  ",
"   .OOOOOOOO .OOOOOOOO .OOOOOOOO          =$$   ",
"                                                "};
