.\" Copyright (C) 2012-2024 alx@fastestcode.org
.\" This software is distributed under the terms of the MIT license.
.\" See the included LICENSE file for further information.
.\"
.TH XIMAGING 1
.SH NAME
ximaging \- raster graphics browser/viewer.
.SH SYNOPSIS
ximaging [options] [directory|file]
.SH DESCRIPTION
.PP
XImaging is a graphics image browser and viewer for Unix operating systems
running X11.
.SS Options
.PP
In addition to standard X toolkit options, following can be specified on the
command line:
.TP
\fB\-browse\fP
Open a browser rather than a viewer window when the application is launched
without a file/directory argument.
.TP
\fB\-format\fP <suffix>
Deduce image file format from the suffix specified
(see \fBSUPPORTED FILE FORMATS\fP).
.TP
\fB-f\fP <suffix>
Same as \fB\-format\fP.
.TP
\fB\-pin\fP
Pin newly opened window so it won't be reused.
.TP
\fB\-server\fP
Launch in the background and wait for IPC requests.
(first instance in a session launches as a server by default).
.TP
\fB\-quiet\fP
Don't write anything to stdout.
.SS Operands
.PP
.TP
\fBdirectory\fP
Directory containing images to browse.
.TP
\fBfile\fP
Single image file name to be displayed.
.SH GUI USAGE
.TP
\fBBrowser\fP
The Browser window displays miniature previews of images contained within a
directory. The navigation bar displays the current location and may be used to
input a desired path directly.
.IP
Items displayed in the view area can be selected and manipulated using
either keyboard or mouse. MB1 click selects an item. The selection may be
extended to another item by holding the Shift key, while clicking another item
using MB1. Selection state of a single item may be toggled by clicking on it
using MB1, while holding down the Control key. MB2 behaves the same way as MB1,
except that it displays a pop-up menu with commonly used functions. Double\-
clicking an image with MB1 opens the file in the Viewer. Double\-clicking the
file name with MB1 posts the Rename dialog. Double\-clicking an image, or
pressing enter when the view area is focused, will display the selected file
in a Viewer window.
.IP
Navigation keys may be used to move the focus rectangle among the items.
Pressing the \fISpace\fP key toggles the selection state of
the focused item. Holding the\fIShift\fP key while moving the selection
rectangle extends the selection. The \fITab\fP key may be used to switch
keyboard focus between the view and the navigation bar.
.TP
\fBViewer\fP
The Viewer window is used to display single images, and provides functionality
to zoom in and out, rotate, flip the image, and display multi\-page images.
Note that transformations applied to the image within the viewer are only
temporary, since XImaging doesn't provide destructive image editing capabilities.
The image, if larger than the view, may be panned either by holding MB1 pressed
and dragging the image, or by pushing one of the direction keys on the keyboard.
.TP
\fBWindow Management\fP
By default the last active browser or viewer window is reused when XImaging
receives a file/directory open request, but every window can be configured
to stay within its current state by choosing \fBPin This\fP from its
\fBWindow\fP menu. The initial value for this setting may also be specified as
X resource (see \fBRESOURCES\fP) or using the \fB\-pin\fP command line switch.
.SH RESOURCES
.TP
\fBbrowse\fP \fIBoolean\fP
Open a browser window rather than a viewer window when the application is
launched without a file/directory argument. Default is False.
.TP
\fBconfirmFileRemoval\fP \fIBoolean\fP
Ask before deleting files. Default is True.
.TP
\fBdownsamplingFilter\fP \fIBoolean\fP
Apply filtering when down\-sampling (zooming out) images in the viewer window.
Results in better image quality if enabled, but is computationally intensive,
especially on large images. The default value is True.
\fBNOTE:\fP This option is only supported on true color visuals.
.TP
\fBeditCommand\fP \fIString\fP
A command to be invoked when the \fBEdit\fP item is chosen from the \fBFile\fP
menu. The list of currently selected files will be appended to the end of the
command string specified.
.TP
\fBfastPanning\fP \fIBoolean\fP
If set to True, up/down\-sampling filter in the viewer will be
temporarily disabled when the image is being panned using the mouse.
Only effective if \fBdownsamplingFilter\fP and/or \fBupsamplingFilter\fP
resources are set to True. Default value is False.
.TP
\fBkeyPanAmount\fP \fIInteger\fP
Amount of pixels by which the image in the Viewer is moved per key press.
.TP
\fBlargeCursors\fP \fIBoolean\fP
Use large cursors. Default is \fIFalse\fP.
.TP
\fBlargeToolbarIcons\fP \fIBoolean\fP
Use large icons in toolbar buttons. Default is False.
See also: \fBviewerToolbar\fP resource.
.TP
\fBlockRotation\fP \fIBoolean\fP
Keep rotation settings across images. Default is False.
.TP
\fBpinWindow\fB \fIBoolean\fP
Pin newly opened windows by default so that it won't be reused.
Default is \fIFalse\fP.
.TP
\fBquiet\fP \fIBoolean\fP
Don't write anything to stdout. Default is False.
.TP
\fBrefreshInterval\fP \fIInteger\fP
Time interval in seconds at which XImaging checks for file
and directory content changes. Default is 4 seconds.
.TP
\fBshowDirectories\fB \fIBoolean\fP
Display sub\-directories in a separate pane in the browser window.
Default is True.
.TP
\fBshowDotFiles\fP \fIBoolean\fP
Display files whose names are starting with a dot. Default is True.
.TP
\fBtileAspectRatio\fP \fIInteger:Integer\fP
Aspect ratio of preview tiles in browser window. Default is 4:3.
.TP
\fBtileSize\fP small|medium|large
Default size of preview tiles in browser window. Must be either "small",
"medium", or "large". \fBNOTE:\fP Actual pixel values for these mnemonics
are obtained from \fBtileSizeList\fP and \fBtileAspectRatio\fP resources.
.TP
\fBtileSizeList\fP \fIInteger, Integer, Integer\fP
Comma separated list of three (small, medium, large) tile size values in
pixels. The final size is calculated using the aspect ratio specified with
the \fBtileAspectRatio\fP resource.
.TP
\fBupsamplingFilter\fP \fIBoolean\fP
Apply filtering when up\-sampling (zooming in) images in the viewer window.
Results in a smooth transition between zoomed\-in pixels. Default value is
\fIFalse\fP. \fBNOTE:\fP This option is only supported on true color visuals.
.TP
\fBviewerToolbar\fP \fIBoolean\fP
If set to \fITrue\fP, a toolbar containing some of the most frequently used
commands will be shown in the viewer window. The default value is False.
.TP
\fBvisualProgress\fP \fIBoolean\fP
Display the image in the viewer window as it is being loaded.
Default is \fITrue\fP.
.TP
\fBzoomFit\fP \fIBoolean\fP
Shrink the image to fit the viewer window. Default is True.
.TP
\fBzoomIncrement\fP \fI<1.1 - 4.0>\fP
Specifies the increment value for the zoom-in/out function. Must be in the
1.1 - 4.0 range. Default is 1.6.
.SH SUPPORTED FILE FORMATS
.PP
.nf
JPEG Image (jpg, jpeg, jpe, jif, jfif, jfi)
MS-Windows Bitmap (bmp) - BMP V3+, uncompressed only
PC-Paintbrush V5 (pcx)
Portable Network Graphics (png)
Silicon Graphics Image (sgi, rgb, rgba, int, inta, bw)
Sun Microsystems Raster Image (ras, sun)
Tagged Image File (tif, tiff)
Truevision (tga, tpic)
X/CDE Bitmap (xbm, bm)
X/CDE Pixmap (xpm, pm) - XMP3 only
.fi
.SH AUTHORS
.PP
XImaging was written and is maintained by alx@fastestcode.org
.SH CAVEATS
.PP
XImaging doesn't provide file format conversion features. There are tools -
e.g., ImageMagick (http://www.imagemagick.org) designed for this purpose.
