.\" Copyright (C) 2012-2024 alx@fastestcode.org
.\" This software is distributed under the terms of the MIT license.
.\" See the included LICENSE file for further information.
.\"
.TH XIMAGING 1
.SH NAME
ximaging \- raster graphics browser/viewer.
.SH SYNOPSIS
ximaging [options] [directory|file]
.SH DESCRIPTION
.PP
XImaging is a graphics image browser and viewer for Unix operating systems
running X11.
.SS Options
.PP
In addition to standard X toolkit options, following can be specified on the
command line:
.TP
\fB\-browse\fP
Open a browser rather than a viewer window when the application is launched
without a file/directory argument.
.TP
\fB\-format\fP <suffix>
Deduce image file format from the suffix specified
(see \fBSUPPORTED FILE FORMATS\fP and \fBFILTERS\fP).
.TP
\fB-f\fP <suffix>
Same as \fB\-format\fP.
.TP
\fB\-pin\fP
Pin newly opened window so it won't be reused.
.TP
\fB\-server\fP
Launch in the background and wait for IPC requests.
(first instance in a session launches as a server by default).
.TP
\fB\-quiet\fP
Don't write anything to stdout.
.SS Operands
.PP
.TP
\fBdirectory\fP
Directory containing images to browse.
.TP
\fBfile\fP
Single image file name to be displayed.
.SH GUI USAGE
.TP
\fBBrowser\fP
The Browser window displays miniature previews of images contained within a
directory. The navigation bar displays the current location and may be used to
input a desired path directly.
.IP
Items displayed in the view area can be selected and manipulated using
either keyboard or mouse. MB1 click selects an item. The selection may be
extended to another item by holding the Shift key, while clicking another item
using MB1. Selection state of a single item may be toggled by clicking on it
using MB1, while holding down the Control key. MB2 behaves the same way as MB1,
except that it displays a pop-up menu with commonly used functions. Double\-
clicking an image with MB1 opens the file in the Viewer. Double\-clicking the
file name with MB1 posts the Rename dialog. Double\-clicking an image, or
pressing enter when the view area is focused, will display the selected file
in a Viewer window.
.IP
Navigation keys may be used to move the focus rectangle among the items.
Pressing the \fISpace\fP key toggles the selection state of
the focused item. Holding the\fIShift\fP key while moving the selection
rectangle extends the selection.
.IP
Pressing the \fBBackspace\fP key, while the view area or the directory list is
focused, changes current location to the parent directory.
.TP
\fBViewer\fP
The Viewer window is used to display single images, and provides functionality
to zoom in and out, rotate, flip the image, and display multi\-page images.
Note that transformations applied to the image within the viewer are only
temporary, since XImaging doesn't provide destructive image editing capabilities.
The image, if larger than the view, may be panned either by holding MB1 pressed
and dragging the image, or by pushing one of the direction keys on the keyboard.
.TP
\fBWindow Management\fP
By default the last active browser or viewer window is reused when XImaging
receives a file/directory open request, but every window can be configured
to stay within its current state by choosing \fBPin This\fP from its
\fBWindow\fP menu. The initial value for this setting may also be specified as
X resource (see \fBRESOURCES\fP) or using the \fB\-pin\fP command line switch.
.SH RESOURCES
.SS General Resources
The the application class name is XImaging, class names of its viewer and
browser shell windows are \fBXImagingViewer\fP and \fBXImagingBrowser\fP,
respectively.
.TP
\fBadvanceOnDelete\fP \fIBoolean\fP
If True, the viewer will load next file in the directory, when currently
displayed file is being deleted. Default is True.
.TP
\fBbrowse\fP \fIBoolean\fP
Open a browser window rather than a viewer window when the application is
launched without a file/directory argument. Default is False.
.TP
\fBconfirmFileRemoval\fP \fIBoolean\fP
Ask before deleting files. Default is True.
.TP
\fBdownsamplingFilter\fP \fIBoolean\fP
Apply filtering when down\-sampling (zooming out) images in the viewer window.
Results in better image quality if enabled, but is computationally intensive,
especially on large images. The default value is True.
\fBNOTE:\fP This option is only supported on true color visuals.
See also \fBfastPanning\fP.
.TP
\fBeditCommand\fP \fIString\fP
A command to be invoked when the \fBEdit\fP item is chosen from the \fBFile\fP
menu. The list of currently selected files will be appended to the end of the
command string specified.
.TP
\fBfastPanning\fP \fIBoolean\fP
If set to True, up/down\-sampling filter in the viewer will be
temporarily disabled when the image is being panned using the mouse.
Only effective if \fBdownsamplingFilter\fP and/or \fBupsamplingFilter\fP
resources are set to True. Default value is False.
.TP
\fBkeyPanAmount\fP \fIInteger\fP
Amount of pixels by which the image in the Viewer is moved per key press.
.TP
\fBlargeCursors\fP \fIBoolean\fP
Use large cursors. Default is \fIFalse\fP.
.TP
\fBlargeToolbarIcons\fP \fIBoolean\fP
Use large icons in toolbar buttons. Default is False.
See also: \fBviewerToolbar\fP resource.
.TP
\fBlockRotation\fP \fIBoolean\fP
Keep rotation settings across images. Default is False.
.TP
\fBpinWindow\fB \fIBoolean\fP
Pin newly opened windows by default so that it won't be reused.
Default is \fIFalse\fP.
.TP
\fBquiet\fP \fIBoolean\fP
Don't write anything to stdout. Default is False.
.TP
\fBrefreshInterval\fP \fIInteger\fP
Time interval in seconds at which XImaging checks for file
and directory content changes. Default is 4 seconds.
.TP
\fBshowDirectories\fB \fIBoolean\fP
Display sub\-directories in a separate pane in the browser window.
Default is True.
.TP
\fBshowDotFiles\fP \fIBoolean\fP
Display files whose names are starting with a dot. Default is True.
.TP
\fBtileAspectRatio\fP \fIInteger:Integer\fP
Aspect ratio of preview tiles in browser window. Default is 4:3.
.TP
\fBtileSize\fP small|medium|large
Default size of preview tiles in browser window. Must be either "small",
"medium", or "large". \fBNOTE:\fP Actual pixel values for these mnemonics
are obtained from \fBtileSizeList\fP and \fBtileAspectRatio\fP resources.
.TP
\fBtileSizeList\fP \fIInteger, Integer, Integer\fP
Comma separated list of three (small, medium, large) tile size values in
pixels. The final size is calculated using the aspect ratio specified with
the \fBtileAspectRatio\fP resource.
.TP
\fBupsamplingFilter\fP \fIBoolean\fP
Apply filtering when up\-sampling (zooming in) images in the viewer window.
Results in a smooth transition between zoomed\-in pixels. Default value is
\fIFalse\fP. \fBNOTE:\fP This option is only supported on true color visuals.
.TP
\fBviewerToolbar\fP \fIBoolean\fP
If set to \fITrue\fP, a toolbar containing some of the most frequently used
commands will be shown in the viewer window. The default value is False.
.TP
\fBvisualProgress\fP \fIBoolean\fP
Display the image in the viewer window as it is being loaded.
Default is \fITrue\fP.
.TP
\fBzoomFit\fP \fIBoolean\fP
Shrink the image to fit the viewer window. Default is True.
.TP
\fBzoomIncrement\fP \fI<1.1 - 4.0>\fP
Specifies the increment value for the zoom-in/out function. Must be in the
1.1 - 4.0 range. Default is 1.6.
.SS Path Field Widget Resources
The path field widget consists of a text field that displays the current
working directory with an array of push buttons, each representing an element
of the path, above\.
.PP
The class name of the widget is \fBPathField\fP, the widget name
\fBpathField\fP. Aside from resources described below, the widget inherits
resources from XmManager(3)\.
.TP
\fBbuttonHeight \fIInteger\fP\fP
A value in percent that sets the vertical size of path element buttons
relative to the height of the font used to draw text in the widget\.
Default is 100\.
.TP
\fBcompactPath\fP \fIBoolean\fP
If True, the $HOME part of the path will be represented by a tilde\.
Default is true\.
.SH SUPPORTED FILE FORMATS
.PP
.nf
JPEG Image (jpg, jpeg, jpe, jif, jfif, jfi)
MS-Windows Bitmap - BMP V3+, uncompressed only (bmp)
Netpbm - Portable Any Map, Type 4 to 7 (pbm, pgm, ppm, pam)
PC-Paintbrush V5 (pcx)
Portable Network Graphics (png)
Silicon Graphics Image (sgi, rgb, rgba, int, inta, bw)
Sun Microsystems Raster Image (ras, sun)
Tagged Image File (tif, tiff)
Truevision (tga, tpic)
X/CDE Bitmap (xbm, bm)
X/CDE Pixmap (xpm, pm) - XMP3 only
.fi
.PP
Support for additional image types is available through filters.
.SH FILTERS
.PP
A filter is an executable program that can read a particular image format and
write its contents to the stdout in PNM (Netpbm) format, which XImaging will
then read and display.
.PP
To use a filter, XImaging needs to know the executable's file name, and what
image name suffixes it should be invoked for. This is defined by two mandatory
and one optional Xresource records.
.PP
.nf
XImaging.filter.<\fBfilter_name\fP>: <\fBexecutable_file_name\fP>
XImaging.filter.<\fBfilter_name\fP>.suffixes: <\fBlist_of_suffixes\fP>
XImaging.filter.<\fBfilter_name\fP>.description: <\fBtype_description\fP>
.fi
.PP
\fBfilter_name\fP may be any string adhering to X resource specification.
.PP
\fBexecutable_file_name\fP specifies the file name of the filter executable
and its arguments, in which the placeholder \fB%n\fP is expanded to the
image file name.
.PP
\fBlist_of_suffixes\fP should contain one or more, space separated, file name
suffixes (without the dot character) this filter should be invoked for.
.PP
\fBtype_description\fP is optional and specifies the descriptive text to be
displayed in viewer's status area, which defaults to PNM data type if omitted.
.PP
\fBFilter examples using \fIconvert\fP (ImageMagick) and \fIxcf2pmn\fP
(xcftools):\fP
.PP
.nf
XImaging.filter.imagemagick: convert %n pam:-
XImaging.filter.imagemagick.suffixes: svg gif psd

XImaging.filter.gimp: xcf2pnm -c -b #ffffff %n
XImaging.filter.gimp.suffixes: xcf
XImaging.filter.gimp.description: GIMP Image
.fi
.SH AUTHORS
.PP
XImaging was written and is maintained by alx@fastestcode.org
.SH CAVEATS
.PP
XImaging doesn't provide file format conversion features. There are tools \-
e.g., ImageMagick (http://www.imagemagick.org) \- designed for this purpose.
