$ -----------------------------------------------------------------------------
$ Copyright (C) 2012-2017 alx@fastestcode.org
$ This software is distributed under the terms of the MIT license.
$ See the included LICENSE file for further information.
$ -----------------------------------------------------------------------------
$ XImaging string sets
$ Underscore character in menu item strings indicates a mnemonic
$ -----------------------------------------------------------------------------

$ -----------------------------------------------------------------------------
$set 1 - viewer menu
$ -----------------------------------------------------------------------------

1 _File
2 _Open...
3 _Browse...
4 Browse _Here
5 _Close
6 _Edit
7 _Next File
8 _Previous File

20 _View
21 _Refresh
22 _Properties
23 _Next Page
24 Pr_evious Page
25 _Toolbar

30 _Zoom
31 Zoom _In
32 Zoom _Out
33 Original _Size
34 _Fit To Window

40 _Rotate
41 Flip _Vertically
42 Flip _Horizontally
43 Rotate _Left
44 Rotate _Right
45 R_eset
46 L_ock

50 _Edit
51 _Copy To...
52 _Move To...
53 _Rename...
54 _Delete

60 _Window
61 _Pin This
62 _Open New

100 _Help
101 _Manual
102 _About

$ -----------------------------------------------------------------------------
$set 2 - browser menu
$ -----------------------------------------------------------------------------
1 _File
2 _Browse...
3 _Edit
4 _Display
5 _Close

20 _View
21 _Refresh
23 _Properties
24 _Small Tiles
25 _Medium Tiles
26 _Large Tiles

30 _Window
31 _Pin This
32 _Open New

40 _Edit
41 Select _All
42 Select _None
43 _Invert Selection
44 _Copy To...
45 _Move To...
46 _Rename
47 _Delete

100 _Help
101 _Manual
102 _About

$ -----------------------------------------------------------------------------
$set 3 - application messages
$ -----------------------------------------------------------------------------

1 No appropriate visual found.
2 Shared memory extension not available.
3 Ignoring redundant arguments.
4 Unable to initialize desktop services.
5 ToolTalk service not available.
6 ToolTalk message delivery failed.
7 Fatal error
8 Unable to initialize desktop media exchange.
9 Loading...
10 Ready
11 Unsupported image format.
12 Invalid or damaged image file.
13 An error occured while reading the file.
14 Not enough resources available for this task.
15 No permission to access the specified file.
16 The specified file is invalid.
17 XImaging is already serving this display.
18 XImaging was built with the CDE/ToolTalk IPC support, but the static \
ptype is not registered within the CDE type database. Other ToolTalk aware \
applications won't be able to communicate with XImaging. See the README file \
included with the application and/or the application manpage for information \
on how to fix this.
19 Couldn't retrieve the desktop color palette.
20 Warning
21 Multithreading support in the X Toolkit required.
22 Could not open file.
23 File already exists. Overwrite?
24 Error processing the file:
25 No image
26 Error reading directory.
27 Reading directory...
28 Processing...
29 The file will be irrevocably removed. Continue?
30 Selected files will be irrevocably removed. Continue?
31 No image files in current directory.
32 The action couldn't be completed.
33 Files
34 No items to display
35 Selected
36 File already exists.
37 Another instance of XImaging appears to be running, but is not responding.

$ -----------------------------------------------------------------------------
$set 4 - dialog messages
$ -----------------------------------------------------------------------------

1 Yes
2 No
3 OK
4 Cancel
5 Retry
6 Dismiss
7 Help
8 Open File
9 Open Directory
10 Source
11 Destination
12 Copying
13 Moving
14 Deleting
15 Select Destination
16 Specify a new name for
17 Rename
18 Delete
19 Width
20 Height
21 Depth
22 Date
23 Size

